server:
  port: 9000
  
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hireitbit2022@gmail.com
    password: rforlblemawlhvra
    properties:
      mail:
        smtp:
          starttls:
            enabled: true
          auth: true
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hireit.cmhewpu1kdn3.us-west-1.rds.amazonaws.com:3306/hireit?serverTimezone=Asia/Seoul
    username: admin
    password: qlsnWkd0729
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
mybatis:
  type-aliases-package: com.hire.it.mapper,com.hire.it.dto
  mapper-locations:
  - /mapper/**/*.xml
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
  
#logging:
#  level:
#    com.hire.it: DEBUG
